import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css"
import { Toaster } from "sonner";
import MobileNav from "@/components/MobileNav";
import DesktopNav from "@/components/DesktopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
          <DesktopNav />
          <div className="flex w-full justify-around pb-10">
            {children}
          </div>
        </div>
        <MobileNav />
        <Toaster />
      </body>
    </html>
  );
}
